wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.6
    start_time: 1637482747
    t:
      1:
      - 1
      - 5
      - 9
      2:
      - 1
      - 5
      - 9
      4: 3.8.6
      5: 0.12.7
      8:
      - 5
